#pragma once
#include <SDL2/SDL.h>
#include <string>
#include <unordered_map>
#include <memory>

class Input
{
public:
	//------------------Enumerated----------------
	/// A type of input action.
	enum ActionType {
		/// The button/key was down and is now up.
		Pressed,
		/// The button/key was down in the previous update and is still down.
		StillDown,
		/// The button/key was up in the previous update and is still up.
		StillUp,
		/// The button/key was down in this update (previous state is not considered).
		Down,
		/// The button/key was up in this update (previous state is not considered).
		Up,
		Held
	};

	//-----------------Struct--------------------
	/// Represents a key action.
	struct InputAction
	{
		SDL_Scancode actionKey;

		SDL_JoyButtonEvent gamepadButton;

		InputAction(SDL_Scancode actionKey)
		{
			this->actionKey = actionKey;
		}
	};
	//------------------Constructors-------------
	Input();
	~Input();
	//-------------------Functions---------------
	/// Checks the SDL event structs for stuff
	void PollEvent();
	/// This should be called every frame
	void UpdateKeyboardState();
	/// 
	bool ActionOccured(std::string actionName, ActionType actionType);
	//-------------------Variables---------------

private:
	//-------------------Functions---------------
	//Probably won't be using this one anymore
	void On_Key_Up(SDL_Keysym);
	/// Checks keyboard states to determine if a key was pressed
	/// @param key keyboard key id
	/// @return bool True if pressed, False if not
	bool KeyPressed(SDL_Scancode key);
	/// Checks keyboard states to determine if a key is being held
	/// @param key keyboard key id
	/// @return bool True if held, False if not
	bool KeyHeld(SDL_Scancode key);
	//-------------------Variables---------------
	//state of keyboard == relevant key presses and actions
	/// State of the keyboard in the previous frame
	const Uint8 *prevKeyboardState;
	/// State of the keyboard in the current frame
	const Uint8 *curKeyboardState;
	//These ones don't actually work or exist.  Create a struct
	//to handle gamepad states
	Uint8 *prevGamepadState;
	Uint8 *curGamepadState;
	/// Structure that holds all events generated by SDL
	SDL_Event generalEvent;
	/// State of some key press
	SDL_KeyboardEvent keyEvent;
	/// State of some gamepad button press
	SDL_JoyButtonEvent gamepadButtonEvent;
	/// This names and stores relevant keystrokes
	std::unordered_map<std::string, std::shared_ptr<InputAction>> actionMap;
};